name: Verify Commit

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      - name: Lint
        run: pnpm exec nx run-many --parallel -t lint stylelint
      - name: Build
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: pnpm build
      - name: Test
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: pnpm test
